-- Add price fields to booking_inquiries table
ALTER TABLE public.booking_inquiries 
ADD COLUMN IF NOT EXISTS total_price NUMERIC(10, 2) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS price_per_night NUMERIC(10, 2) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS nights INTEGER DEFAULT NULL,
ADD COLUMN IF NOT EXISTS cleaning_fee NUMERIC(10, 2) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS service_fee NUMERIC(10, 2) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS bed_linen_fee NUMERIC(10, 2) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS tourist_tax_total NUMERIC(10, 2) DEFAULT NULL;